### ISSUE TITLE
VerificationMethod defined but not used

### ISSUE THREAD

**Issue by fhirfly** [veramolabs/ens-did-resolver#6]
### Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ x] I am running the latest version
- [ x] I checked the documentation and found no answer
- [x ] I checked to make sure that this issue has not already been filed

### Current Behavior

C:\Users\richb\Projects\ens-did-resolver\src\helpers.ts
  1:10  warning  'VerificationMethod' is defined but never used  @typescript-eslint/no-unused-vars

### Expected Behavior

verificationMethod is properly taken from org.w3c.did.verificationMethod in ENS TEXT if present

### Failure Information

Please help provide information about the failure.

#### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. run yarn package
2. watch the build
3. Run the resolver on did:ens:fhirfly.eth
4. verificationMethod is not constructed from TEXT key. 

#### Environment Details

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

#### Failure Logs/Screenshots

Please include any relevant log snippets or files here.
Create a [GIST](https://gist.github.com) which is a paste of your _full or sanitized_ logs, and link them here.
Please do _NOT_ paste your full logs here, as it will make this issue very long and hard to read!

#### Alternatives you considered

Please provide details about an environment where this bug does not occur.

---

**Comment by fhirfly** [comment]
code looks like it considers verificationMethod in resolver.ts in line 138

**Comment by mirceanis** [comment]
This was fixed in #4
Thank you for reporting
